docker-compose-yaml: ./lagoon-docker-compose.yml

project: laravel-example-simple

tasks:
  post-rollout:
    - run:
        name: Prepare Storage
        command: mkdir -p /app/storage/framework/sessions /app/storage/framework/views /app/storage/framework/cache /app/storage/framework/cache/data
        service: cli
    - run:
        name: Run migrations
        command: php artisan migrate --force
        service: cli
    - run:
        name: Run config:clear
        command: php artisan config:clear
        service: cli
    - run:
        name: Run config:cache
        command: php artisan config:cache
        service: cli
    - run:
        name: Run optimize
        command: php artisan optimize
        service: cli

# environments:
#  prod:
#    cronjobs:
#      - name: artisan schedule
#        schedule: "* * * * *"
#        command: cd /app && php artisan schedule:run
#        service: cli
